spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: info
    com.kuzminac.loan_service.loan_calculator: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
